<div class="alert alert-block alert-success">

<b>CODING BACKPROPAGATION FROM SCRATCH: ON A SINGLE NEURON</b>
</div>

In [7]:
import numpy as np 

# initialize parameters 
inputs =  np.array([1.0, -2.0, 3.0])
weights = np.array([-3.0, -1.0, 2.0])
bias = 1.0
target_output = 0
learning_rate = 0.001

def relu(x):
    return np.maximum(x, 0)

def relu_derivative(x):
    return np.where(x>0, 1.0, 0)

for i in range(20):
    # Forward pass 
    sum = np.dot(inputs, weights) + bias
    output = relu(sum)
    loss = (output - target_output)**2

    # Backward pass
    dloss_doutput = 2 * (output - target_output)
    doutput_drelu = relu_derivative(sum)
    dmul_dwi = inputs
    dmul_dbias = 1.0

    dloss_dwi = dloss_doutput * doutput_drelu * dmul_dwi
    dloss_dbi = dloss_doutput * doutput_drelu * dmul_dbias

    # Update the weights and bias
    weights = weights - learning_rate * dloss_dwi
    bias = bias - learning_rate * dloss_dbi

    # Print the loss for this iteration
    print(f"Iteration {i+ 1}, Loss: {loss}")

print(f"Final Loss {loss}")
print(f"Final Bias {bias}")


Iteration 1, Loss: 36.0
Iteration 2, Loss: 33.872399999999985
Iteration 3, Loss: 31.870541159999995
Iteration 4, Loss: 29.98699217744401
Iteration 5, Loss: 28.21476093975706
Iteration 6, Loss: 26.54726856821742
Iteration 7, Loss: 24.978324995835766
Iteration 8, Loss: 23.502105988581878
Iteration 9, Loss: 22.113131524656684
Iteration 10, Loss: 20.80624545154949
Iteration 11, Loss: 19.576596345362915
Iteration 12, Loss: 18.419619501351963
Iteration 13, Loss: 17.331019988822064
Iteration 14, Loss: 16.306756707482677
Iteration 15, Loss: 15.343027386070442
Iteration 16, Loss: 14.43625446755368
Iteration 17, Loss: 13.583071828521266
Iteration 18, Loss: 12.780312283455652
Iteration 19, Loss: 12.024995827503426
Iteration 20, Loss: 11.314318574097976
Final Loss 11.314318574097976
Final Bias 0.8175177371706989


<div class="alert alert-block alert-success">
<b>BACKPROPAGATION </b>
</div>

<div class="alert alert-block alert-warning">
GRADIENTS OF THE LOSS WITH RESPECT TO WEIGHTS
</div>

In [1]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# We have 3 sets of inputs - samples
inputs = np.array([[1, 2, 3, 2.5],
 [2., 5., -1., 2],
 [-1.5, 2.7, 3.3, -0.8]])
# sum weights of given input
# and multiply by the passed-in gradient for this neuron

dweights = np.dot(inputs.T, dvalues)
print(dweights)

[[ 0.5  0.5  0.5]
 [20.1 20.1 20.1]
 [10.9 10.9 10.9]
 [ 4.1  4.1  4.1]]


<div class="alert alert-block alert-warning">
GRADIENTS OF THE LOSS WITH RESPECT TO BIASES
</div>

In [2]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# One bias for each neuron
# biases are the row vector with a shape (1, neurons)
biases = np.array([[2, 3, 0.5]])
# dbiases - sum values, do this over samples (first axis), keepdims
# since this by default will produce a plain list -

dbiases = np.sum(dvalues, axis= 0, keepdims= True)
print(dbiases)


[[6. 6. 6.]]


<div class="alert alert-block alert-warning">
GRADIENTS OF THE LOSS WITH RESPECT TO INPUTS
</div>

In [3]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# We have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]).T
# sum weights of given input
# and multiply by the passed-in gradient for this neuron

dinputs = np.dot(dvalues, weights.T)
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]


## Definition of Layer with backpropagation

In [ ]:
class Layer:
    def __init__(self, row, cols):
        self.weights = 0.01 * np.random.randn(row, cols)
        self.bias = np.ones((1, cols))

    def forward(self, inputs):
        self.x = inputs
        output = np.dot(self.x, self.weights) + self.bias
        return output

    def backward(self, dvalues):
        self.dL_dz = dvalues
        self.dL_dweights = np.dot(self.x.T, self.dL_dz  )
        self.dL_dbias = np.sum(self.dL_dz, axis = 0, keepdims= True)
        self.dL_dinputs = np.dot(self.dL_dz, self.weights.T)

## Definition of ReLU activation function with backpropagation


In [3]:
class relu:
    def forward(self, inputs):
        self.inputs = inputs
        output = np.maximum(0, inputs)
        return output
    
    def backward(self, dvalues):
        self.dL_dz = dvalues.copy()
        self.dL_dz[self.inputs <= 0] = 0